services:
  - type: web
    name: coxy-frontend
    env: docker
    plan: starter
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DOMA_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
    rootDir: frontend
