services:
  - type: worker
    name: coxy-twitter-bot
    env: docker
    plan: starter
    dockerfilePath: domain-monitor/twitter-bot/Dockerfile
    dockerContext: domain-monitor/twitter-bot
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_ACCESS_TOKEN
        sync: false
      - key: TWITTER_ACCESS_TOKEN_SECRET
        sync: false
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: MAX_TWEETS_PER_DAY
        value: 20
      - key: TWEET_INTERVAL
        value: 3600000
    autoDeploy: true
    branch: main
    rootDir: domain-monitor/twitter-bot
